apiVersion: v1
kind: ServiceAccount
metadata:
  name: ctf-player
  namespace: default
---
# access in default namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ctf-player
  namespace: default
rules:
- apiGroups:
    - "*"
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ctf-player
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ctf-player
subjects:
- kind: ServiceAccount
  name: ctf-player
  namespace: default
# access in secret namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: secret-namespace
  name: ctf-player
rules:
- apiGroups: ["*"]
  resources: ["pods", "flags", "deployments", "configMaps", "services", "ingress"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ctf-player
  namespace: secret-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ctf-player
subjects:
- kind: ServiceAccount
  name: ctf-player
  namespace: default
# access to cluster wide resources
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ctf-player
  namespace: default
rules:
- apiGroups:
    - "*"
  resources: ["namespaces", "customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ctf-player
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ctf-player
subjects:
- kind: ServiceAccount
  name: ctf-player
  namespace: default
