#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

if [ -z "${WHISPER_REAL_FLAG:-}" ]; then
    WHISPER_REAL_FLAG='R3CTF{placeholder_local_dev_flag_set_real_via_env}'
fi
export WHISPER_REAL_FLAG

if [ -z "${WHISPER_FLAG_KEY:-}" ]; then
    if [ -f .flag_key ]; then
        WHISPER_FLAG_KEY="$(cat .flag_key)"
    else
        WHISPER_FLAG_KEY="$(python3 -c 'import secrets; print(secrets.token_hex(24))')"
        printf '%s' "${WHISPER_FLAG_KEY}" > .flag_key && chmod 600 .flag_key
    fi
fi
export WHISPER_FLAG_KEY
export WHISPER_FLAG_TEMPLATE="${WHISPER_FLAG_TEMPLATE:-whisper-rcard-0click}"

export WHISPER_ADMIN_TOKEN="${WHISPER_ADMIN_TOKEN:-ctf-admin-token-7a4p1vq0}"
export WHISPER_WEB_PORT="${WHISPER_WEB_PORT:-31337}"
export WHISPER_BACKEND_PORT="${WHISPER_BACKEND_PORT:-31338}"

export PUBLIC_IP="${1:-${PUBLIC_IP:-127.0.0.1}}"

_ARG_N="${2:-}"
if [ -n "${_ARG_N}" ]; then
    WHISPER_MAX_INSTANCES="${_ARG_N}"
fi
WHISPER_MAX_INSTANCES="${WHISPER_MAX_INSTANCES:-2}"
if ! printf '%s' "${WHISPER_MAX_INSTANCES}" | grep -qE '^[1-9][0-9]*$'; then
    echo "[run] ERROR: max-instances must be a positive integer, got '${WHISPER_MAX_INSTANCES}'" >&2
    exit 1
fi
export WHISPER_MAX_INSTANCES

if docker compose version >/dev/null 2>&1; then
    DC="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
    DC="docker-compose"
else
    echo "[run] Docker Compose not found. Install the v2 plugin (docker compose) or the v1 binary (docker-compose)." >&2
    exit 1
fi

GEN_FILE="docker-compose.victims.gen.yml"

echo "[run] Generating ${GEN_FILE} with ${WHISPER_MAX_INSTANCES} victim(s)..."

POOL_JSON='['
SERVICES_YAML=""
VICTIM_NAMES=""

for i in $(seq 1 "${WHISPER_MAX_INSTANCES}"); do
    SERVICE="whisper-victim-${i}"
    VICTIM_NAMES="${VICTIM_NAMES} ${SERVICE}"

    if [ "${i}" -gt 1 ]; then
        POOL_JSON="${POOL_JSON},"
    fi
    POOL_JSON="${POOL_JSON}{\"id\":\"${i}\",\"runner\":\"http://${SERVICE}:9090\",\"victim\":\"victim-${i}\"}"

    PADDED_I=$(printf '%04d' "${i}")
    VICTIM_PHONE="+1555${PADDED_I}"

    SERVICES_YAML="${SERVICES_YAML}
  ${SERVICE}:
    build:
      context: ..
      dockerfile: deploy/victim-runner/Dockerfile
    privileged: true
    devices:
      - /dev/kvm:/dev/kvm
    environment:
      WHISPER_REAL_FLAG: \"\${WHISPER_REAL_FLAG}\"
      BACKEND_URL: \"http://backend:8000\"
      BACKEND_HOST: \"backend\"
      BACKEND_PORT: \"8000\"
      INSTANCE_ID: \"${i}\"
      VICTIM_HANDLE: \"victim-${i}\"
      VICTIM_PHONE: \"${VICTIM_PHONE}\"
      VICTIM_DISPLAY: \"Whisper Victim ${i}\"
      AVD_NAME: \"whisper_victim_${i}\"
      RUNNER_HOST: \"0.0.0.0\"
      RUNNER_PORT: \"9090\"
    networks:
      default:
        aliases:
          - ${SERVICE}
    expose:
      - \"9090\"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: [\"CMD\", \"python3\", \"-c\",
             \"import urllib.request; r=urllib.request.urlopen('http://localhost:9090/health',timeout=5); import json; d=json.loads(r.read()); assert d.get('boot') is True\"]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 600s
    restart: unless-stopped
"
done

POOL_JSON="${POOL_JSON}]"

cat > "${GEN_FILE}" <<GENEOF
# AUTO-GENERATED by run.sh -- do not edit by hand.
# N=${WHISPER_MAX_INSTANCES} victim runner(s).
# Re-generated on every run.sh invocation.

services:
${SERVICES_YAML}
  judge-web:
    environment:
      WHISPER_POOL: '${POOL_JSON}'
GENEOF

echo "[run] Generated ${GEN_FILE} (pool: ${POOL_JSON})"

export WHISPER_POOL="${POOL_JSON}"

echo "[run] Tearing down any existing stack (and its data)..."
$DC -f docker-compose.yml -f "${GEN_FILE}" down -v --remove-orphans >/dev/null 2>&1 || true

echo "[run] Building and starting proxy + backend + judge-web + ${WHISPER_MAX_INSTANCES} victim(s)..."
$DC -f docker-compose.yml -f "${GEN_FILE}" up -d --build \
    proxy backend judge-web ${VICTIM_NAMES}

FIRST_VICTIM="whisper-victim-1"
echo "[run] Waiting for ${FIRST_VICTIM} to finish booting (first boot ~10-15 min)..."
for _ in $(seq 1 360); do
    $DC -f docker-compose.yml -f "${GEN_FILE}" logs "${FIRST_VICTIM}" 2>/dev/null \
        | grep -q READY && break
    sleep 10
done

if $DC -f docker-compose.yml -f "${GEN_FILE}" logs "${FIRST_VICTIM}" 2>/dev/null \
        | grep -q READY; then
    echo
    echo "[run] Server up (${WHISPER_MAX_INSTANCES} victim(s) warming up in background)."
    echo "      judge:   http://${PUBLIC_IP}:${WHISPER_WEB_PORT}"
    echo "      backend: http://${PUBLIC_IP}:${WHISPER_BACKEND_PORT}"
    echo "      pool:    ${WHISPER_MAX_INSTANCES} victim runner(s)"
    echo "      tokens:  config/teams.json"
    echo
    echo "[run] FLAG KEY (set this same value in your scoring platform's flag checker;"
    echo "      keep it secret -- anyone with it can forge every team's flag):"
    echo "        WHISPER_FLAG_KEY=${WHISPER_FLAG_KEY}"
else
    echo "[run] ${FIRST_VICTIM} did not report READY in time; check:"
    echo "      $DC -f docker-compose.yml -f ${GEN_FILE} logs ${FIRST_VICTIM}"
    exit 1
fi
