difficulty=peaceful
force-gamemode=true
gamemode=adventure
generate-structures=false
generator-settings={"layers"\:[],"biome"\:"minecraft\:the_void","structures"\:false}
level-type=flat
max-players=1
motd=Welcome to 2026 R3Craft\!
online-mode=false
op-permission-level=0
